--1.FIND TOP 5 MOST ORDERED CATEGORY.
SELECT CATEGORY,SUM (QTY) AS QUANTITY FROM SALES
GROUP BY CATEGORY
ORDER BY QUANTITY DESC
LIMIT 5;

--2.IDENTIFY TOP 2 PRODUCT CATEGORIES IN EACH STATE BASED ON TOTAL REVENUE GENRATED.
WITH CATEGORY_SALES AS (
 SELECT SHIP_STATE,CATEGORY,ROUND(SUM(AMOUNT)::NUMERIC,0) AS GENRATED_AMOUNT
 FROM SALES
 WHERE STATUS='Shipped - Delivered to Buyer'
 GROUP BY SHIP_STATE,CATEGORY
 ),
RANKED_CATEGORY AS (
 SELECT SHIP_STATE,CATEGORY,GENRATED_AMOUNT,
 DENSE_RANK()OVER(PARTITION BY SHIP_STATE ORDER BY GENRATED_AMOUNT DESC ) AS RANKING
 FROM CATEGORY_SALES 
 )
SELECT SHIP_STATE,CATEGORY,GENRATED_AMOUNT,RANKING
FROM RANKED_CATEGORY
WHERE RANKING <=2
ORDER BY SHIP_STATE  ;

--3.SEGMENT DAY TYPE  AND CALCULATE THE PERCENTAGE OF TOTAL ORDER FOR EACH SEGMENT.
WITH DAY_TYPE_ORDER AS(
 SELECT
 CASE WHEN EXTRACT(DOW FROM DATE) IN(0,6) THEN 'WEEKEND'
 ELSE 'WEEKDAY'
 END AS DAY_TYPE,
 COUNT (ORDER_ID)AS TOTAL_ORDER
 FROM SALES
 WHERE STATUS='Shipped - Delivered to Buyer'
 GROUP BY DAY_TYPE
 ),
 TOTAL_ORDERS AS(
 SELECT SUM(TOTAL_ORDER)AS ORDERS
 FROM DAY_TYPE_ORDER
 )
SELECT W.DAY_TYPE,W.TOTAL_ORDER,
ROUND((W.TOTAL_ORDER*100/T.ORDERS)::NUMERIC,2) AS REV_PERCENTAGE
FROM DAY_TYPE_ORDER W
CROSS JOIN TOTAL_ORDERS T;


--4.CALCULATE THE PERCENTAGE OF AMOUNT  BY EACH ORDER STATUS.
WITH TOTAL AS(
SELECT STATUS,ROUND(SUM (AMOUNT)::NUMERIC,0) AS TOTAL_SUM
FROM SALES
GROUP BY STATUS),
AMOUNT_TOTAL AS(
SELECT SUM(TOTAL_SUM) AS SUM_AMOUNT
FROM TOTAL
)
SELECT T.STATUS,
ROUND((T.TOTAL_SUM/A.SUM_AMOUNT *100)::NUMERIC,2) AS STATUS_PERCENT
FROM TOTAL T
CROSS JOIN AMOUNT_TOTAL A
WHERE T.TOTAL_SUM IS NOT NULL
ORDER BY STATUS_PERCENT DESC;


--5.CALCULATE THE PERCENTAGE OF  PER DAY  REVENUE AND PER DAY ORDERED QUANTITY.
WITH DAILY_ORDER AS(
 SELECT
 EXTRACT(MONTH FROM DATE) AS ORDER_MONTH,
 EXTRACT(DAY FROM DATE) AS ORDER_DAY,
 TRIM(TO_CHAR( DATE, 'DAY')) 
 AS DAY_NAME,
 SUM (QTY)AS TOTAL_ORDER,
 SUM(AMOUNT)AS PER_DAY_REV
 FROM SALES
 WHERE STATUS='Shipped - Delivered to Buyer'
 GROUP BY DAY_NAME,ORDER_MONTH,ORDER_DAY
 ORDER BY ORDER_MONTH,ORDER_DAY
 ),
 TOTAL_REV AS(
 SELECT SUM(PER_DAY_REV)AS REV
 FROM DAILY_ORDER
 )
SELECT D.ORDER_MONTH,D.ORDER_DAY,D.DAY_NAME,D.TOTAL_ORDER,D.PER_DAY_REV,
ROUND((D.PER_DAY_REV*100/T.REV)::NUMERIC,2) AS REV_PERCENTAGE
FROM DAILY_ORDER D
CROSS JOIN TOTAL_REV T;

--6.CALCULATE THE PERCENTAGE OF MONTHLY  REVENUE AND  ORDERED QUANTITY.
WITH MONTH_ORDER AS(
 SELECT
 EXTRACT(MONTH FROM DATE) AS ORDER_MONTH,
 COUNT(DISTINCT DATE) AS TOTAL_DAYS,
 SUM (QTY)AS TOTAL_ORDER,
 SUM(AMOUNT)AS MONTH_REV
 FROM SALES
 WHERE STATUS='Shipped - Delivered to Buyer'
 GROUP BY ORDER_MONTH
 ORDER BY ORDER_MONTH
 ),
 TOTAL_REV AS(
 SELECT SUM(MONTH_REV)AS REV
 FROM MONTH_ORDER
 )
SELECT D.ORDER_MONTH,D.TOTAL_ORDER,D.MONTH_REV,D.TOTAL_DAYS,
ROUND((D.MONTH_REV*100/T.REV)::NUMERIC,2) AS REV_PERCENTAGE
FROM MONTH_ORDER D
CROSS JOIN TOTAL_REV T;

--7.FIND  HIGHEST NUMBER OF RETURNED PRODUCT .
SELECT CATEGORY,SKU,
COUNT(*) AS TOTAL_ORDER,
SUM(CASE WHEN STATUS='Cancelled' THEN 1 ELSE 0 END) AS CANCEL_ORDERS,
SUM(CASE  WHEN STATUS IN('Shipped - Returned to Seller',
                         'Shipped - Returning to Seller')
	THEN 1 ELSE 0 END) AS RETURN_ORDERS
FROM SALES
GROUP BY CATEGORY,SKU
ORDER BY RETURN_ORDERS DESC,CANCEL_ORDERS DESC;

--8.CALCULATE WEEKLY TOTAL DILIVERED ORDER AND REVENUE.
SELECT  
COUNT(*) AS TOTAL,SUM(AMOUNT),
DATE_TRUNC('WEEK', DATE) AS WEEKS
FROM SALES
WHERE STATUS= 'Shipped - Delivered to Buyer'
GROUP BY WEEKS
ORDER BY WEEKS;
