--IDENTIFY DUPLICATES.
SELECT ORDER_ID,SKU,COUNT(*)FROM SALES
GROUP BY ORDER_ID,SKU
HAVING COUNT(*)>1;

--DELETE DUPLICATED ROWS.
DELETE FROM SALES A
USING SALES B 
WHERE A.CTID>B.CTID
AND A.ORDER_ID=B.ORDER_ID
AND A.SKU=B.SKU

--DELETE COLUMNS.
ALTER TABLE SALES
DROP COLUMN INDEX

--1.TOTAL ORDERS
select count(order_id) as total_orders from sales;

--2.TOTAL REVENUE FROM DILIVERD PRODUCT.
SELECT ROUND(SUM(AMOUNT::NUMERIC),2) AS REVENUE FROM SALES
WHERE STATUS='Shipped - Delivered to Buyer';

--3.FIND CANCELLED  ORDERS WITH TOTAL AMOUNT OVER CATEGORY.
SELECT CATEGORY,COUNT(ORDER_ID) AS CANCELLED_ORDER,ROUND(SUM(AMOUNT::NUMERIC),0) AS AMOUNT 
FROM SALES
WHERE STATUS='Cancelled'
GROUP BY CATEGORY
ORDER BY CANCELLED_ORDER DESC;

--4.FIND TOP 5 MOST ORDERED CATEGORY.
SELECT CATEGORY,SUM (QTY) AS QUANTITY FROM SALES
GROUP BY CATEGORY
ORDER BY QUANTITY DESC
LIMIT 5;

--5.RANK PRODUCT CATEGORIES  WITHIN EACH STATE BY REVENUE GENRATED, ONLT TOP 3 CATEGORY PER STATE.
WITH CATEGORY_SALES AS (
 SELECT SHIP_STATE,CATEGORY,ROUND(SUM(AMOUNT)::NUMERIC,0) AS GENRATED_AMOUNT
 FROM SALES
 GROUP BY SHIP_STATE,CATEGORY
 ),

RANKED_CATEGORY AS (
 SELECT SHIP_STATE,CATEGORY,GENRATED_AMOUNT,
 DENSE_RANK()OVER(PARTITION BY SHIP_STATE ORDER BY GENRATED_AMOUNT DESC ) AS RANKING
 FROM CATEGORY_SALES 
 )

SELECT SHIP_STATE,CATEGORY,GENRATED_AMOUNT,RANKING
FROM RANKED_CATEGORY
WHERE RANKING <=3
ORDER BY SHIP_STATE,RANKING;

--CALCULATE THE MEDIAN AMOUNT.
SELECT
 PERCENTILE_CONT(0.5)
 WITHIN GROUP(ORDER BY AMOUNT)AS 
MEDIAN_AMOUNT
FROM SALES;

--6.SEGMENT DAY TYPE  AND CALCULATE THE PERCENTAGE OF TOTAL ORDER FOR EACH SEGMENT.
WITH DAY_TYPE_ORDER AS(
 SELECT
 CASE WHEN EXTRACT(DOW FROM DATE) IN(0,6) THEN 'WEEKEND'
 ELSE 'WEEKDAY'
 END AS DAY_TYPE,
 COUNT (ORDER_ID)AS TOTAL_ORDER
 FROM SALES
 WHERE STATUS='Shipped - Delivered to Buyer'
 GROUP BY DAY_TYPE
 ),
 TOTAL_ORDERS AS(
 SELECT SUM(TOTAL_ORDER)AS ORDERS
 FROM DAY_TYPE_ORDER
 )
SELECT W.DAY_TYPE,W.TOTAL_ORDER,
ROUND((W.TOTAL_ORDER*100/T.ORDERS)::NUMERIC,2) AS REV_PERCENTAGE
FROM DAY_TYPE_ORDER W
CROSS JOIN TOTAL_ORDERS T;

--7.CALCULATE THE PERCENTAGE OF AMOUNT  BY EACH ORDER STATUS.
WITH TOTAL AS(
SELECT STATUS,ROUND(SUM (AMOUNT)::NUMERIC,0) AS TOTAL_SUM
FROM SALES
GROUP BY STATUS),
AMOUNT_TOTAL AS(
SELECT SUM(TOTAL_SUM) AS SUM_AMOUNT
FROM TOTAL
)
SELECT T.STATUS,
ROUND((T.TOTAL_SUM/A.SUM_AMOUNT *100)::NUMERIC,2) AS STATUS_PERCENT
FROM TOTAL T
CROSS JOIN AMOUNT_TOTAL A
WHERE T.TOTAL_SUM IS NOT NULL
ORDER BY STATUS_PERCENT DESC;

--8.CALCULATE THE PERCENTAGE OF  PER DAY  REVENUE AND ORDERED QUANTITY.
WITH DAILY_ORDER AS(
 SELECT
 EXTRACT(MONTH FROM DATE) AS ORDER_MONTH,
 EXTRACT(DAY FROM DATE) AS DAYS,
 TRIM(TO_CHAR( DATE, 'DAY')) 
 AS DAY_NAME,
 SUM (QTY)AS TOTAL_ORDER,
 SUM(AMOUNT)AS PER_DAY_REV
 FROM SALES
 WHERE STATUS='Shipped - Delivered to Buyer'
 GROUP BY DAY_NAME,ORDER_MONTH,DAYS
 ORDER BY ORDER_MONTH,DAYS
 ),
 TOTAL_REV AS(
 SELECT SUM(PER_DAY_REV)AS REV
 FROM DAILY_ORDER
 )
SELECT D.ORDER_MONTH,D.DAYS,D.DAY_NAME,D.TOTAL_ORDER,D.PER_DAY_REV,
ROUND((D.PER_DAY_REV*100/T.REV)::NUMERIC,2) AS REV_PERCENTAGE
FROM DAILY_ORDER D
CROSS JOIN TOTAL_REV T;

--9.STYLE LEVEL CANCELED PRODUCT WITH CANCELLATION RATE.
SELECT CATEGORY,STYLE,SIZE,AMOUNT,
SUM(CASE 
     WHEN STATUS='Cancelled' THEN QTY ELSE 0 END)AS CANCELLED_UNITS,
SUM(QTY) AS TOTAL_UNITS,
ROUND(SUM(CASE  WHEN STATUS='Cancelled' THEN QTY ELSE 0 END)* 100.0/NULLIF(SUM(QTY),0),2) AS CANCELLED_RATE
FROM SALES
GROUP BY CATEGORY,STYLE,SIZE,AMOUNT
HAVING SUM(QTY)>100
ORDER BY CANCELLED_RATE DESC;


--AVERAGE CANCELLATION RATE
SELECT 
ROUND(SUM(CASE WHEN STATUS='Cancelled' THEN QTY ELSE 0 END)*100.0
/SUM(QTY),2) AS OVERALL_CANCEL_RATE
FROM SALES